# GitHub Issue Forms :: Issue Templates

# allow users to create a blank issue form
blank_issues_enabled: true

# let user display certain messages when creating a issues
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
